<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="/subscribe" method="post">
    <input type="hidden" value="1" name="subscriber">
    <input type="hidden" value="2" name="subscribedTo">
    <button type="submit">OK</button>
</form>
</body>
</html>